package tenprojecteulersolutionsinjava;

/*Fibonacci Numbers Problem 2
from https://projecteuler.net/problem=2

The problem is as follows: 
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
4 million = 4, 000, 000

ERRORS: currently prints all 0's 
*/

import java.util.Scanner;

public class EvenFibonacci 
{
	static long[] fibArray = new long[20]; // change from 10 to accommodate index size!

	public static void main(String[] args) 
	{
		Scanner input = new Scanner(System.in);
	    System.out.print("Enter an index for the Fibonacci number: ");
         int index = input.nextInt();

         fib(index);
         
         
         for(int i = 0; i < getFib().length; i++)
         {
         System.out.println("fibArray[" + i + "] = " + fibArray[i]);
         }
         
         input.close();
	
	//System.out.println("fib a index " + index + " is " + fib(index));

	} // close main() 
	
	



	public static long fib(long n) // index
	{
		
		long fib0 = 0;
		long fib1 = 1;
		long fib2 = 2;
		
		//long fib;
		storeFib(n);
		if (n == 0) 
		{
			//n = 0;
			storeFib(fib0);
			return fib0;
		}
		
		//if (index == 1) 
		else if (n == 1) 
			{
			//n = 1; 
			storeFib(fib1);
			return fib1;
			}
		else if (n == 2)
		{
			return fib2;
		}
			
		for (int i = 3; i <= n; i++)
		{
			fib0= fib1;
			fib1 = fib2;
			fib2 = fib0 + fib1;
			storeFib(fib2);
		}
		return fib2; 
		//{
		//fib = fib(index - 1) + fib(index - 2); 
			//fib = fib(fib - 1) + fib(fib - 2); 

		//storeFib(n);
	//return fib;
		//}
				
	}
	
	public static void storeFib(long fibNum)
	{ 
		
		int counter = 0;
		//static long[] fibArray = new long[20]; // change from 10 to accomodate index size!
		fibArray[counter] = fibNum;
		counter++;

		
	} // close storeFib()
	
	
	public static void setFib(long fibNUm)
	{
		
		
	}
	
	public static long[] getFib()
	{
		//fibArray = fibArray;
		return fibArray;
	}
	

} // CLOSE CLASS 
