package tenprojecteulersolutionsinjava;
/*Fibonacci Numbers Problem 2
from https://projecteuler.net/problem=2

The problem is as follows: 
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
4 million = 4, 000, 000


*/

public class Fibonacci
{

	public static void main(String[] args) 
	{
		//int sum = 0;
		int N = 10;
		int[] fibonacciArray = new int[N];
	
		fibonacciArray[0] = 0;
		fibonacciArray[1] = 1;
for (int i = 2; i < N; i++)
{
	
	

		fibonacciArray[i] = fibonacciArray[i - 2] + fibonacciArray[i -1];
	
	System.out.println("fibonacciArray[" + i + "] is " + fibonacciArray[i]);
}

for (int j = 0; j < fibonacciArray.length; j++)
{
	System.out.println("fibonacci[" + j + "] is" + fibonacciArray[j]);
}

	} // close main()

}
